### DISCUSSION TITLE
How to make a pdns recursor make records requests to several dns servers

### DISCUSSION THREAD

**Discussion by stanislassimus** [PowerDNS/pdns#14760] [Q&A]
Good day to all. At the moment, our company has a Windows DNS server that serves the test.local zone, we wanted to smoothly switch to powerDNS. At the moment, there is a need for the pdns recursor, when clients access it, to check for a record first on powerDNS and then on the Windows server and give a response. How can this be done?

**Comment by stanislassimus** [comment]
**recursor.conf**
```
#dnssec:
  # validation: process # default
#  trustanchorfile: /usr/share/dns/root.key
recursor:
  hint_file: /usr/share/dns/root.hints
  include_dir: /etc/powerdns/recursor.d
  setgid: pdns
  setuid: pdns
  #forward_zones_file: /etc/powerdns/recursor-forward.zones
  forward_zones:
    - zone: test.local
      forwarders:
        - 127.0.0.1:5300 #powerdns authorative server
        - 192.168.4.15 #windows dns server
      recurse: false

    - zone: 10.in-addr.arpa
      forwarders:
        - 127.0.0.1:5300
      recurse: true
incoming:
  listen:
   - 0.0.0.0:53 # default
  allow_from:
   - 0.0.0.0/0
   - 10.0.0.0/8
   - 127.0.0.1
#outgoing:
 # source_address:
 # - 0.0.0.0 # default
#packetcache:
  #ttl: 600
#logging:
recordcache:
 max_ttl: 100
```
