### DISCUSSION TITLE
Logining PDNS recursor and DNSDist

### DISCUSSION THREAD

**Discussion by chelezo** [PowerDNS/pdns#14893] [Q&A] [answered]
Good evening! I do everything according to the manuals but I still couldn't get the logs to be written to separate files. The latest stable services are installed, the Ubuntu server is 22.04. Can someone post the part of the configuration that works with logging!? Thanks in advance!

**Comment by Habbie** [comment]
Our software does not directly log to files, in most cases. You need to configure some part of your OS (journald, (r)syslogd) to make your logs go where you want them to go.

**Reply by chelezo** [reply]
> Our software does not directly log to files, in most cases. You need to configure some part of your OS (journald, (r)syslogd) to make your logs go where you want them to go.

Yes, I set it up according to the manuals, but there is still no result ((((

**Reply by Habbie** [reply]
then you need to show us how you set it up - otherwise we definitely cannot help

**Reply by chelezo** [reply]
```
recursor dnssec:
  validation: off
incoming:
  listen:
  - 10.18.20.144:5301
logging:
  facility: '1'
  loglevel: 7
# cat /etc/rsyslog.d/pdns.conf
local1.info                       -/var/log/pdns.info
local1.warn                       -/var/log/pdns.warn
local1.err                        /var/log/pdns.err
```
