### DISCUSSION TITLE
powerdns recursor uses only 1 core

### DISCUSSION THREAD

**Discussion by chelezo** [PowerDNS/pdns#14902] [Q&A]
powerdns recursor for some reason uses only one core out of 4 available (on stress test one core was loaded at 100% while the others were free)
![photo_2024-11-28_22-49-42](https://github.com/user-attachments/assets/839127d8-2e6e-49f5-bbdc-06de9d31e6e1)

**Comment by rgacogne** [comment]
Please share your configuration..

**Reply by chelezo** [reply]
```
dnssec:
  validation: off
incoming:
  listen:
  - 10.8.2.144:5301
logging:
  facility: '1'
  loglevel: 7
recursor:
   forward_zones:
     - zone: tests.lans
       forwarders:
       - 10.8.2.141:5350
     - zone: mps.lan
       forwarders:
       - 10.8.2.141:5350
   forward_zones_recurse:
     - zone: .
       recurse: true
       forwarders:
       - 10.10.10.4:53
   threads: 4
```
