### DISCUSSION TITLE
How to check for high memory in the recursor process

### DISCUSSION THREAD

**Discussion by chunyuliu106667777** [PowerDNS/pdns#15268] [Q&A]
Description：

I am conducting an experiment where I built a Docker image of Ubuntu 22.04 and ran the container of the image. I successfully started a recursive service inside the container.  At first, the process only used 9% of the server's memory, but after running for a while, I found through the top command that the process used more than 70% of the server's memory and continued to rise. Eventually, the process was killed by the system due to OOM. How can I investigate where the problem lies. Can you give me some suggestions for checking? Thanks a lot.

Information：
1. Running instructions：`/usr/sbin/pdns_recursor --daemon=no --write-pid=no --disable-syslog --log-timestamp=no`
2. Configuration (recursor.yml)：
```
dnssec:
  validation: off
recursor:
  hint_file: no-refresh
  include_dir: /etc/powerdns/recursor.d
  any_to_tcp: true
  lua_config_file: /etc/powerdns/config.lua
  lua_dns_script: /etc/powerdns/script.lua
  lua_maintenance_interval: 30
  threads: 4
  forward_zones_recurse:
    - zone: .
      forwarders:
        - 8.8.8.8
incoming:
  allow_from:
    - 0.0.0.0/0
    - "::/0"
  gettag_needs_edns_options: true
  port: 53
  listen:
    - 127.0.0.1
```
