### DISCUSSION TITLE
dnsdist 2.0:  experimenting the new YAML syntax

### DISCUSSION THREAD

**Discussion by dmachard** [PowerDNS/pdns#15350] [General]
Hi

I am experimenting with the new YAML syntax and trying to add the following rule for queries, but I encounter the following error on startup.

```
dnsdistv2-1  | dnsdist 2.0.0-alpha1 comes with ABSOLUTELY NO WARRANTY. This is free software, and you are welcome to redistribute it according to the terms of the GPL version 2
dnsdistv2-1  | terminate called after throwing an instance of 'std::runtime_error'
dnsdistv2-1  |   what():  Lua action '' could not be created: no valid function name, Lua code or Lua file

```

Config rule

```yaml
query_rules:
  - name: "add ip in proxy protocol"
    selector:
      type: QNameSuffix
      suffixes:
        - powerdns.com
    action:
      type: Lua
      function_name: addProxyProtocolVal
      function_code: |
        function addProxyProtocolVal(dq)
          dq:addProxyProtocolValue(1, dq.localaddr:tostring())
          return DNSAction.None
        end
```

Am I missing something, or is it a bug?

Denis
