### DISCUSSION TITLE
AX FDP

### DISCUSSION THREAD

**Discussion by littlechicks** [PowerDNS/pdns#15391] [Q&A]
hi, is anyone tried to make AF_XDP working with dockerized dnsdist ?

i followed systemd installation : https://www.dnsdist.org/advanced/xsk.html#running-under-systemd

I tried to run dnsdist with (
```
privileged: true
    cap_add:
      - SYS_ADMIN  
      - NET_RAW   
    ulimits:
      memlock:
        soft: -1
        hard: -1  # Permet de verrouiller toute la mémoire (pour AF_XDP et autres)
    restart: always  # Optionnel, pour redémarrer le service en cas d'échec
    deploy:
      resources:
        limits:
          memory: 2g

``` 
and mounted the volumes:       

`- /sys/fs/bpf:/sys/fs/bpf  # with chown to 953.`

and set sysctl  kernel.unprivileged_bpf_disabled=0
insalled bcc with `apt-get install bpfcc-tools linux-headers-$(uname -r)`
i run the `xdp.py` programm on ens160.
But when i add xdp instruct in `dnsdist.conf` and run it but i get: 
```
stack traceback:
        [C]: in function 'newXsk'
        [string "chunk"]:17: in main chunk
dnsdist 2.0.0-alpha1 comes with ABSOLUTELY NO WARRANTY. This is free software, and you are welcome to redistribute it according to the terms of the GPL version 2
Fatal Lua error: [string "chunk"]:17: Caught exception: Error creating a umem of size 134217728: Unknown error -1
```
