### ISSUE TITLE
TSIG key is missing with gmysql backend

### ISSUE THREAD

**Issue by timiion** [PowerDNS/pdns#11475]
- Program: Authoritative 
 - Issue type: Bug report

### Short description

When I execute the command pdnsutil to generate a TSIG key, the key value can not be found in gmysql database.

### Environment

 - Operating system: Ubuntu 20.04
 - Software version: 4.6.1 
 - Software source: Docker with powerdns/pdns-auth-46:latest

### Steps to reproduce

1. $ Use pdnsutil tool to generate a TSIG key.  

```
$ pdnsutil generate-tsig-key test hmac-md5  
Create new TSIG key test hmac-md5 TGs9AUW1qaKz8CvNPWRCB3IK/QN58lNeoVbYBmo3y3k=
```

2.  Check the TSIG key with pdnsutil tool is Ok.

```
$ pdnsutil list-tsig-keys  
test. hmac-md5. TGs9AUW1qaKz8CvNPWRCB3IK/QN58lNeoVbYBmo3y3k=
```

3. Check from gmysql database, it's not working.

```
MariaDB [(none)]> select * from pdns.tsigkeys;
Empty set (0.000 sec)

```

4. I can manually insert TSIG key to gmysql successfully.
```
MariaDB [(none)]> INSERT INTO pdns.tsigkeys (`id`, `name`, `algorithm`, `secret`) VALUES (NULL, 'testdata', 'hamc-md5', '819bwGPsPxSnSXj7RVVcZGYpfAP1SYbpW9Xk3ozrV6s=');
Query OK, 1 row affected (0.001 sec)

MariaDB [(none)]> select * from pdns.tsigkeys;
+----+----------+-----------+----------------------------------------------+
| id | name     | algorithm | secret                                       |
+----+----------+-----------+----------------------------------------------+
|  6 | testdata | hamc-md5  | 819bwGPsPxSnSXj7RVVcZGYpfAP1SYbpW9Xk3ozrV6s= |
+----+----------+-----------+----------------------------------------------+
1 row in set (0.000 sec)
```
5. I can check the TSIG key above setp 4 from pdnsutil tool.
```
$ pdnsutil list-tsig-keys
test. hmac-md5. TGs9AUW1qaKz8CvNPWRCB3IK/QN58lNeoVbYBmo3y3k=
testdata. hamc-md5. 819bwGPsPxSnSXj7RVVcZGYpfAP1SYbpW9Xk3ozrV6s=
```
6. Same problem with webserver API to generate a TSIG key, the key can not be found in gmysql database.

### Expected behaviour

When the backend is gmysql, use pdnsutil tool or webserver API to generate TSIG key, the key value should be found in gmysql database.

### Actual behaviour

The TSIG key is missing in gmysql backend when using pdnsutil tool or webserver API to generate it.

### Other information

Database tables use schema file in docker powerdns/pdns-auth-46:latest at /usr/local/share/doc/pdns/schema.mysql.sql.

**Comment by Habbie** [comment]
Can you show your config?

**Comment by timiion** [comment]
Thanks for you note, I am sorry for the delay in responding. Here is my config, there are 3 files as below:

> .
> ├── docker-compose.yml
> ├── pdns.conf
> └── schema.mysql.sql

Dump schema.mysql.sql from docker container:
```
docker run -d --name pdns powerdns/pdns-auth-46
docker cp pdns:/usr/local/share/doc/pdns/schema.mysql.sql ./
docker rm -f pdns
```


docker-compose.yml
```
version: "3"

services:
  mariadb:
    image: mariadb
    container_name: mariadb
    environment:
      - MYSQL_RANDOM_ROOT_PASSWORD=yes
      - MYSQL_USER=pdns
      - MYSQL_PASSWORD=pdns
      - MYSQL_DATABASE=pdns
    volumes:
      - ./schema.mysql.sql:/docker-entrypoint-initdb.d/schema.mysql.sql

  pdns:
    image: powerdns/pdns-auth-46
    container_name: pdns
    restart: unless-stopped
    environment:
      - PDNS_AUTH_API_KEY=changeme
    volumes:
      - ./pdns.conf:/etc/powerdns/pdns.d/pdns.conf
    depends_on:
      - mariadb

```
pdns.conf
```
launch+=gmysql
gmysql-host=mariadb
gmysql-user=pdns
gmysql-password=pdns
gmysql-dbname=pdns
gmysql-port=3306

```
Use docker-compose to start up the PowerDNS. 
```
~/pdns$ docker-compose up -d
Creating network "pdns_default" with the default driver
Creating mariadb ... done
Creating pdns    ... done
~/pdns$
~/pdns$ docker exec -it pdns pdnsutil generate-tsig-key test hmac-md5
Create new TSIG key test hmac-md5 jHuAexzoBOv7zyaeqQGqsLCOWrGhL3MWVkTrvCIPUkI=
~/pdns$
~/pdns$ docker exec -it pdns pdnsutil list-tsig-keys
test. hmac-md5. jHuAexzoBOv7zyaeqQGqsLCOWrGhL3MWVkTrvCIPUkI=
~/pdns$
~/pdns$ docker exec -it mariadb mysql -updns -ppdns -e 'select * from pdns.tsigkeys'
~/pdns$
~/pdns$ docker exec -it mariadb mysql -updns -ppdns -e "INSERT INTO pdns.tsigkeys (id, name, algorithm, secret) VALUES (NULL, 'testdata', 'hamc-md5', '819bwGPsPxSnSXj7RVVcZGYpfAP1SYbpW9Xk3ozrV6s=')"
~/pdns$
~/pdns$ docker exec -it mariadb mysql -updns -ppdns -e 'select * from pdns.tsigkeys'
+----+----------+-----------+----------------------------------------------+
| id | name     | algorithm | secret                                       |
+----+----------+-----------+----------------------------------------------+
|  1 | testdata | hamc-md5  | 819bwGPsPxSnSXj7RVVcZGYpfAP1SYbpW9Xk3ozrV6s= |
+----+----------+-----------+----------------------------------------------+
~/pdns$
~/pdns$ docker exec -it pdns pdnsutil list-tsig-keys
test. hmac-md5. jHuAexzoBOv7zyaeqQGqsLCOWrGhL3MWVkTrvCIPUkI=
testdata. hamc-md5. 819bwGPsPxSnSXj7RVVcZGYpfAP1SYbpW9Xk3ozrV6s=

```
