### ISSUE TITLE
`sdig` always returns zero status exit code. Return different status codes. 

### ISSUE THREAD

**Issue by KES777** [PowerDNS/pdns#12118]
### Short description
I want to use `sdig` at `healthcheck` 

### Usecase
Whant to monitor container

### Description
https://stackoverflow.com/q/74163549/4632019

I have next config at docker-compose:
```
    healthcheck:
      test: [ "CMD", "host", "-W", "1", "-t", "AAAA", "www.google.com", "172.22.22.23" ]
      interval: 35s
      timeout: 4s
```

But this does not work:
```
OCI runtime exec failed: exec failed: unable to start container process: exec: "host": executable file not found in $PATH: unknown
```

I have tried to change `host` command by `sdig`, but it returns always zero exit status code.

Would be nice if it returns different status codes depending on response from domain name server.
