### ISSUE TITLE
Allow to configure PowerDNS via PDNS_ variables at docker-compose.yml

### ISSUE THREAD

**Issue by KES777** [PowerDNS/pdns#12176]
- Program: Authoritative, Recursor, dnsdist
 - Issue type: Feature request

### Short description
It would be handy if:
>Any setting from https://doc.powerdns.com/3/authoritative/settings/ is supported. Just add the prefix "PDNS_" and replace any hyphens (-) with underscore (_). Example:
>`allow-axfr-ips ===> PDNS_ALLOW_AXFR_IPS`

Like here https://hub.docker.com/r/arzahsze/docker-powerdns

### Usecase

```
services:
  auth:
    cap_add:
      - NET_ADMIN
    restart: unless-stopped
    build:
      context: ./
      dockerfile: Dockerfile-auth
    volumes:
      - ./pdns.conf:/etc/powerdns/pdns.conf
      - pdns-run:/var/run/pdns
      - pdns-data:/var/lib/powerdns
    environment:
      PDNS_GPGSQL_PASSWORD: $PDNS_DB_PASSWORD
      PDNS_LOGLEVEL: 10
```
