### ISSUE TITLE
geoipbackend+pdnsutil check-zone fails silently, should error clearly

### ISSUE THREAD

**Issue by rumato163** [PowerDNS/pdns#12253]
- Program: Authoritative
 - Issue type: Bug report

### Short description
 Getting an error "[Error] No NS record at zone apex in zone" while trying to check any zone via pdnsutil

### Environment

 - Operating system: 5.15.26-gentoo
 - Software version: pdns 4.4.1
 - Software source: Operating system repository

### Steps to reproduce
1. Install and configure pdns with geoip backend
```
cat /etc/powerdns/pdns-geo.conf
config-dir=/etc/powerdns
daemon=yes
setgid=pdns
setuid=pdns
socket-dir=/run
guardian=no

default-ttl=300
distributor-threads=5
receiver-threads=5

local-address=...
local-address-nonexist-fail=no
local-port=53
reuseport=yes

log-dns-details=yes
log-dns-queries=no
log-timestamp=yes
loglevel=12

master=yes
allow-axfr-ips=...

launch=geoip
geoip-database-files=mmdb:/etc/powerdns/geo/GeoIP2-City.mmdb
geoip-zones-file=/etc/powerdns/geo/geo.yml
```
2. create at least one zone in geo.yml
```
cat /etc/powerdns/geo/geo.yml
domains:
- domain: domain.com
  ttl: 300
  records:
    domain.com:
      - soa: ns-geo.domain.com. domain.com. 1 7200 3600 86400 60
      - ns: ns-geo.domain.com
      - a: 127.0.0.1
    ns-geo.domain.com:
      -a: 127.0.0.2
```

3. run "pdnsutil --config-name=geo check-zone domain.com"

### Expected behaviour
Opened MMDB database /etc/powerdns/geo/GeoIP2-City.mmdb(type: GeoIP2-City version: 2.0)
Checked 2 records of 'domain.com', 0 errors, 0 warnings.

### Actual behaviour
Opened MMDB database /etc/powerdns/geo/GeoIP2-City.mmdb(type: GeoIP2-City version: 2.0)
[Error] No NS record at zone apex in zone 'domain.com'
Checked 0 records of 'domain.com', 1 errors, 0 warnings.

### Other information

I was trying to update pdns up to 4.6.2. Still the same
