### ISSUE TITLE
Cannot bind to port 53 on Docker

### ISSUE THREAD

**Issue by TwentyWasHere** [PowerDNS/pdns#12270]
- Program: Authoritative
 - Issue type: Bug report

I am running pdns auth and wanted to switch to containers for my DNS setup for convenience (easy to fire up on another box). When I start the container I get the following error message:

> Dec 06 01:26:56 Listening on controlsocket in '/var/run/pdns/pdns.controlsocket'
> Dec 06 01:26:56 Unable to bind UDP socket to '0.0.0.0:53': Permission denied
> Dec 06 01:26:56 Fatal error: Unable to bind to UDP socket

No more details in the log on loglevel 7. 

I am using the official docker image (powerdns/pdns-auth-47). 

I saw in the readme that you mentioned NET_BIND_SERVICE. This was set, even though according to your readme this is not needed for the docker version (20.10.x) I am running. I tried on several boxes with other distributions and it's the same on all.

As soon as I use a non-privileged port pdns auth starts. It's not a biggie as I can change ports, but the container should run as provided, and under docker should have no issues to bind to that port.

### Steps to reproduce
Start container with default settings on docker as provided

### Expected behaviour
pdns is able to bind to port 53

### Actual behaviour
pdns cannot bind to bind to port 53

**Comment by Habbie** [comment]
This works for 99% of users, but I'm not sure what differs in the 1%. Can you describe your setup? (distro, selinux, apparmor, I don't know, etc.)

**Comment by Bodenhaltung** [comment]
Sounds like Network in Hostmode?

**Comment by TwentyWasHere** [comment]
> This works for 99% of users, but I'm not sure what differs in the 1%. Can you describe your setup? (distro, selinux, apparmor, I don't know, etc.)

Tested on stock Debian Bullseye and Ubuntu 20.04.5 LTS. Also tried disabling apparmor with "seccomp:unconfined.", which made no difference.

Reproducible for me with with the below docker-compose (pdns config only contains local-address/local-port and backend for testing).
```
version: '3.8'
services:
  powerdns_auth:
    container_name: powerdns_auth
    image: powerdns/pdns-auth-47:latest
    restart: unless-stopped
    volumes:
      - /var/lab/docker/powerdns/pdns.conf:/etc/powerdns/pdns.conf
    networks:
      powerdns:
        ipv4_address: 172.53.0.30
    ports:
      - "53:53"
      - "53:53/udp"
      - "8081:8081"
      
networks:
  powerdns:
    name: powerdns
    ipam:
      driver: default
      config:
        - subnet: 172.53.0.0/24
          gateway: 172.53.0.1
```
No other container has any issues for my binding to a port < 1024, pdns auth so far is the only one.

Sure, this is no showstopper as I can bind to any other port I want, but I am still puzzled because I never encountered that issue before with containers, therefore I am curious what "special" things you do around binding time that docker doesn't like here.
