### ISSUE TITLE
return the same servers for ifurlup when all servers are down as when all servers are up

### ISSUE THREAD

**Issue by thestinger** [PowerDNS/pdns#12789]
Consider the following `ifurlup` set when using the options `{selector='all', backupSelector='all'}`: `{{'canada1', 'canada2'}, {'france1', 'france2'}}`. When all the servers are up, it uses `{'canada1', 'canada2'}`. When all servers are down, it currently uses `{'canada1', 'canada2', 'france1', 'france2'}`. We don't want it returning a combination of all the sets (server regions, in our case) any time PowerDNS is restarted or in a case where the health check is broken for some reason. It's possible that someone wants the current `backupSelector='all'` behavior but I don't think it's the common case.

**Comment by Habbie** [comment]
Hello,

it is unclear what you are asking for. We have an issue template so it is easy for us to see the difference between "what you see" and "what you want/expect". Please update this ticket to use the issue template.

**Comment by thestinger** [comment]
My request is to delete this loop and instead use the first vector in candidates, to make the behavior when all servers are down the same as when all servers are up:

https://github.com/PowerDNS/pdns/blob/d0f9cf5ffce41174a7df49b635e6e7e968e9db34/pdns/lua-record.cc#L642-L646

**Comment by thestinger** [comment]
I've come up with a workaround to get the behavior I want. Here's a simplified example:

```yaml
na.geo.releases.grapheneos.org: &releases_north_america
  - lua: A "; x = ifurlup('https://releases.grapheneos.org/cheetah-stable', {{'167.114.114.114', '51.79.74.15', '51.222.159.48', '51.222.140.199'}, {'141.94.71.158', '141.94.71.72', '135.125.183.155', '141.95.0.242'}}, {backupSelector='all'}); return {x[1], x[2], x[3], x[4]}"
  - lua: AAAA "; x = ifurlup('https://releases.grapheneos.org/cheetah-stable', {{'2607:5300:201:3100::6210', '2607:5300:205:200::2441', '2607:5300:205:200::3f46', '2607:5300:205:200::39fe'}, {'2001:41d0:304:200::14ff', '2001:41d0:304:200::a687', '2001:41d0:701:1100::2ec9', '2001:41d0:701:1100::3e56'}}, {backupSelector='all'}); return {x[1], x[2], x[3], x[4]}"
eu.geo.releases.grapheneos.org: &releases_europe
  - lua: A "; x = ifurlup('https://releases.grapheneos.org/cheetah-stable', {{'141.94.71.158', '141.94.71.72', '135.125.183.155', '141.95.0.242'}, {'167.114.114.114', '51.79.74.15', '51.222.159.48', '51.222.140.199'}}, {backupSelector='all'}); return {x[1], x[2], x[3], x[4]}"
  - lua:  AAAA "; x = ifurlup('https://releases.grapheneos.org/cheetah-stable', {{'2001:41d0:304:200::14ff', '2001:41d0:304:200::a687', '2001:41d0:701:1100::2ec9', '2001:41d0:701:1100::3e56'}, {'2607:5300:201:3100::6210', '2607:5300:205:200::2441', '2607:5300:205:200::3f46', '2607:5300:205:200::39fe'}}, {backupSelector='all'}); return {x[1], x[2], x[3], x[4]}"
```

You can see there are 4 servers in North America and 4 servers in Europe. I want it to return a result with all the servers that are up for the appropriate region. It should then fall back to all the servers that are up in the other region. If all the servers are down, it should return the 4 servers for the appropriate region. The current backupSelector implementation uses the whole set of candidates instead of only the first group, meaning it provides all 8 servers. I've worked around this behavior by manually selecting the first group. However, I think this should be what it does itself.

All the servers being down is the default case when PowerDNS doesn't have an existing result cached, which is part of why I care about it. The other reason is because the checks could start failing as a whole due to an issue on the DNS server side. For example, maybe the checks are configured to use a URL that doesn't exist anymore or the DNS server firewall configuration is accidentally set to block resolution.

I think all servers being detected as up and all servers being detected as down should be treated the same way: return all the results from the first group. I don't think merging all the groups together for the fallback result makes sense.

We have multiple cases where we want to use `ifurlup` and none of them should ever fall back to returning all the servers.

I think the way that we're using it is the common, normal way to use this functionality and I don't think other people would want the current behavior either. It is true that the behavior I want can be implemented on top of `backupSelector='all'` with additional code though, which I figured out, so I no longer care much about this but I think the feature would be more appealing if it worked the way I described. I also think `backupSelector='all`` would be a better default than the current random choice because it matches how PowerDNS behaves elsewhere and provides better load balancing by having downstream resolvers aware of all the servers.
