### ISSUE TITLE
GH Actions: enable IPv6 for tests executed on Docker containers

### ISSUE THREAD

**Issue by romeroalx** [PowerDNS/pdns#12844]
- Program: Authoritative, Recursor, dnsdist 

### Description
The docker daemon available on Ubuntu focal Github Runners does not have IPv6 enabled. Therefore, tests using IPv6 are now being skipped in the CI workflow `build-and-test-all.yml` for all components.

We should find a way to enable IPv6 for the Docker daemon running on Github Runners to be able to run IPv6-related tests again.

**Comment by jiridanek** [comment]
Hey, here's what we are doing, from https://github.com/skupperproject/skupper-router/blob/a083d09a9a06da415cecc0d07dee714f3bd487a3/.github/workflows/build.yaml#L418-L422

```
    container:
      image: 'quay.io/${{ matrix.container }}/${{ matrix.container }}:${{ matrix.containerTag }}'
      volumes:
        - ${{github.workspace}}:${{github.workspace}}
      options: --privileged --ulimit core=-1 --security-opt apparmor:unconfined --security-opt seccomp=unconfined --sysctl net.ipv6.conf.all.disable_ipv6=0
```

The important part is `--sysctl net.ipv6.conf.all.disable_ipv6=0` and (maybe, don't know without actually trying) the `--privileged`.
