### ISSUE TITLE
Auth: GeoIP improvement to logging when database fails to be loaded

### ISSUE THREAD

**Issue by nvaatstra** [PowerDNS/pdns#13064]
- Program: Authoritative 
 - Issue type: Feature request

### Short description

Make it easier to see when Auth fails to start because the GeoIP backend is unable to load the configured zone(s)

### Usecase

Auth with multiple configured backends and default logging verbosity could be easier to troubleshoot when it fails to start due to a misconfigured GeoIP zonefile

### Description

When trying to start Auth with multiple backends, including GeoIP (with incorrectly configured zonefile) the logging ends with the following:
```
Jul 24 07:50:01 No GeoIP database files loaded!
Jul 24 07:50:01 Caught an exception instantiating a backend, cleaning up
Jul 24 07:50:01 STL Exception while filling the zone cache: invalid node; this may result from using a map iterator as a sequence iterator, or vice-versa
```
The `No GeoIP database files loaded` is a good hint towards the GeoIP backend, but the `STL Exception while filling the zone cache` was confusing. 

When a reload is issued (on a running Auth, after breaking the zonefile manually) the problem is attributed to the GeoIP backend:
```
GeoIP backend reload failed: invalid node; this may result from using a map iterator as a sequence iterator, or vice-versa
```

The request:
It would be nice if the Auth logging would include a reference to the specific backend when it logs an error that prevents it from starting + indication the zonefile might have a syntax error

Zonefile used to test positive scenario:
```
domains:
  - domain: geo.example.com
    records:
      geo.example.com:
      - soa: ns1.example.com hostmaster.example.com 2014090125 7200 3600 1209600 3600
      - ns: ns1.example.com
    ttl: 30
  ```
  
Example zonefile to generate above errors (ttl is missing):
```
domains:
  - domain: geo.example.com
    records:
      geo.example.com:
      - soa: ns1.example.com hostmaster.example.com 2014090125 7200 3600 1209600 3600
      - ns: ns1.example.com
```
