### ISSUE TITLE
ixfrdist: notify with dualstack listener causes error with ipv4 master

### ISSUE THREAD

**Issue by nvaatstra** [PowerDNS/pdns#13878]
- [x] This is not a support question, I have read [about opensource](https://www.powerdns.com/opensource.html) and will send support questions to the IRC channel, [Github Discussions](https://github.com/PowerDNS/pdns/discussions/) or the mailing list.
- [x] I have read and understood the ['out in the open' support policy](https://blog.powerdns.com/2016/01/18/open-source-support-out-in-the-open/)

 - Program: Authoritative (ixfrdist)
 - Issue type: Bug report

### Short description
When you configure ixfrdist with a dualstack listener (ie: `[::]:9080`) and a `domains` entry with a master with an IPv4 address an error is thrown when ixfrdist receives a NOTIFY over IPv4:

```
msg="Refusing zone4.ixfrdist.local|SOA Notify from [::ffff:127.0.0.1]:16116: Opcode is unsupported (Notify), expected QUERY" prio="Warning"
```

### Steps to reproduce
ixfrdist config:
```
# listener(s)
listen:
  - '[::]:9080'

# webserver
webserver-address: '127.0.0.1:9081'

# working directory
work-dir: /workdir

acl:
  - 0.0.0.0/0
  - ::/0
domains:
- domain: zone4.ixfrdist.local
  master: 127.0.0.1:53
  notify:
  - 1.2.3.4:53
```

When a NOTIFY is sent over IPv4 to ixfrdist for `zone4.ixfrdist.local.` it seems to wrap it into an IPv6 address and when it checks to see if it is valid for notification it seems to try to validate the existence of an IPv6 master (not present) instead of the IPv4 master (present). Seems to be thrown by: https://github.com/PowerDNS/pdns/blob/589dd511f33e009c5aa92f177d2f65b42287c535/pdns/ixfrdist.cc#L668

Tried to workaround the behaviour using the following listeners:
```
listen:
  - '0.0.0.0:9080'
  - '[::]:9080'
```
But this is not possible, as the dualstack listener fails to bind:
```
msg="binding socket to [::]:9080: Address already in use" prio="Error"
```

The concept of the dualstack listener is great, but it would be nice if the IPv4 origin of the request could be considered when performing this source check for a NOTIFY
