### ISSUE TITLE
auth: check-z

### ISSUE THREAD

**Issue by thibmac** [PowerDNS/pdns#15005]
- Program: Authoritative 4.9.3
 - Issue type: Bug report

### Short description
First, apologies if it's just me using it wrong but here's my issue : 
PowerDNS running on a geoip backend does not load RRs in the zones. It can read the YAML zonefile but won't read any RR.

### Environment
Debian 12, pdns 4.9.

### Steps to reproduce
I'm using a pretty basic configuration setup , it can be reproduced even without using any geoip specific records, with the simplest kind of zones: 

```
# pdns.conf
launch=geoip
geoip-database-files=mmdb:/etc/powerdns/geoip/GeoLite2-Country.mmdb
geoip-zones-file=/etc/powerdns/geoip/zones/zones.yml

# /etc/powerdns/geoip/zones/zones.yml
domains:
- domain: localhost
  ttl: 86400
  records:
    localhost:
      - soa: localhost. root.localhost. 20250102 7200 3600 1209600 3600
      - a: 127.0.0.1
      - aaaa: ::1
      - ns: localhost.
```

### Expected behaviour
> pdnsutil list-zone localhost 
I'm expecting to see some RRs here
> pdnsutil check-zone localhost 
Should be correct

### Actual behaviour
```
# pdnsutil check-all-zones                
[Error] No SOA record present, or active, in zone 'localhost'
Checked 0 records of 'localhost', 1 errors, 0 warnings.
Checked 1 zones, 1 had errors.

# pdnsutil list-zone localhost                                                                                                             
$ORIGIN .

```
Whatever I do, it keeps saying "$ORIGIN .".
I have also tried loading different zone from your examples and other online examples and I am always ending up with the same results. 

This doesn't look like an YAML formatting issue either since yq is able to output a coherent

### Other information
For context, I have tried using GEOIP through LUA records but the performance is not great, down to 10% of what a normal bind backend is able to achieve.
I have also tested with the stable debian version (4.7.3)
