### ISSUE TITLE
recursor yaml listen port not respected

### ISSUE THREAD

**Issue by fawaf** [PowerDNS/pdns#15011]
- [ ] This is not a support question, I have read [about opensource](https://www.powerdns.com/opensource.html) and will send support questions to the IRC channel, [GitHub Discussions](https://github.com/PowerDNS/pdns/discussions/) or the mailing list.
- [ ] I have read and understood the ['out in the open' support policy](https://blog.powerdns.com/2016/01/18/open-source-support-out-in-the-open/)

 - Program: Recursor
 - Issue type: Bug report

### Short description
incoming.listen.port and incoming.list ports are not respected in the yaml config

### Environment

 - Operating system: debian linux
 - Software version: 12.8
 - Software source: powerdns repo

### Steps to reproduce

1. config
```incoming:
  listen:
    - '127.0.0.1:5301'
    - listen: '127.0.0.1:5301'
    - 127.0.0.1:5301
  port: 5301
```
1. start/restart recursor

### Expected behaviour

recursor should start of specified port

### Actual behaviour

recursor starts on port 53

**Comment by omoerbeek** [comment]
Please show startup log

**Comment by omoerbeek** [comment]
I tried a few variations here, and they all work. e.g.
```
incoming:
  reuseport: true
  listen:
    - 0.0.0.0:5301
    - '[::]:5301'
```
or
```
incoming:
  reuseport: true
  listen:
    - 0.0.0.0
    - '[::]'
  port: 5301
```
So I'm movibng this to a discussion, as it seems a support question and not an actual code issue.
