### ISSUE TITLE
edns_subnet_allow_list is enabled, public domain name resolution is incorrect

### ISSUE THREAD

**Issue by airsmon** [PowerDNS/pdns#15364]
- [ ] This is not a support question, I have read [about opensource](https://www.powerdns.com/opensource.html) and will send support questions to the IRC channel, [GitHub Discussions](https://github.com/PowerDNS/pdns/discussions/) or the mailing list.
- [ ] I have read and understood the ['out in the open' support policy](https://blog.powerdns.com/2016/01/18/open-source-support-out-in-the-open/)

 - Program: Authoritative, Recursor, dnsdist 
 - Issue type: Bug report

### Environment

 - Operating system: Debian GNU/Linux 12 (bookworm)
 - Software version: powerdns/pdns-recursor-52:5.2.0
 - Software source: 

### Steps to reproduce

1. edns_subnet_allow_list is enabled
```
  edns_subnet_allow_list:
  - 0.0.0.0/0

  forward_zones_recurse:
  - zone: .
    forwarders:
    # google
    - 8.8.8.8
    - 8.8.4.4
```
![Image](https://github.com/user-attachments/assets/3189c7aa-2a42-4e79-825e-7361f5a09590)
2. edns_subnet_allow_list is close

![Image](https://github.com/user-attachments/assets/9df6ca4b-a2c6-408d-9add-9c1f83a53007)
