### ISSUE TITLE
A KV object created in yaml config cannot be referenced to in console

### ISSUE THREAD

**Issue by pfactum** [PowerDNS/pdns#15743]
- Program: dnsdist
 - Issue type: Feature request

### Short description

If a KV store object is created in a yaml config, it seems there's no way to reference it later from a console to get it, for example, reloaded.

### Usecase

Trying to implement adblocking using a list of domains in CDB.

### Description

yaml config example:

```yaml
key_value_stores:
  cdb:
    - name: "blocklist"
      file_name: "/var/lib/dnsdist/blocklist.cdb"
      refresh_delay: 0
  lookup_keys:
    suffix_keys:
      - name: "lookup_suffix"
        wire_format: false
```

Attempt to reload a KV object using its name as specified in yaml config:

```
$ dnsdist -C /etc/dnsdist/config.yml -c -k "…" -e 'blocklist.reload()'
```

It fails:

```
Error: [string "return blocklist.reload()"]:1: attempt to index global 'blocklist' (a nil value)
stack traceback:
        [string "return blocklist.reload()"]:1: in main chunk
```

In console, there should be some way to reference a KV object that is created in yaml config.
