### ISSUE TITLE
Allow a service in geoip-backend to be an array

### ISSUE THREAD

**Issue by tuxis-ie** [PowerDNS/pdns#2757]
It would be cool if a service in a geoip-config could be an array, so that the resolver has multiple options to return, from fine-grained to a default.

eg:

```yaml
domains:
- domain: geocdn.tuxis.net
  ttl: 30
  records:
    geocdn.tuxis.net:
      - soa: ns1.geocdn.tuxis.net hostmaster.tuxis.net 2015091101 7200 3600 1209600 3600
      - ns: ns1.geocdn.tuxis.net
      - ns: ns2.geocdn.tuxis.net
    nld.geocdn.tuxis.net:
      - a: 31.3.104.40
      - txt: Tuxis AS197731
      - aaaa: 2a03:7900:2::31:3:104:40
    as197731.geocdn.tuxis.net:
      - a: 31.3.104.40
      - txt: Tuxis AS197731
      - aaaa: 2a03:7900:2::31:3:104:40
    default.geocdn.tuxis.net:
      - a: 31.3.104.40
      - txt: Tuxis AS197731
      - aaaa: 2a03:7900:2::31:3:104:40
  services:
    cdn.geocdn.tuxis.net: [ '%as.geocdn.tuxis.net', '%co.geocdn.tuxis.net', 'default.geocdn.tuxis.net' ]
```
