### ISSUE TITLE
GeoIP Backend - support more than one domain

### ISSUE THREAD

**Issue by sgreiner** [PowerDNS/pdns#3332]
Hi,

lets say we have the following example geoip_zone_file.yml

```
domains:
- domain: geo.firstdomain.com
  ttl: 3600
  records:
    geo.firstdomain.com:
      - soa: ns1.firstdomain.com hostmaster.firstdomain.com 2016020302 7200 900 3600000 300
      - ns: ns1.firstdomain.com
      - ns: ns2.firstdomain.com
      - mx: 10 mx.firstdomain.com
    deu.service.geo.firstdomain.com:
      - cname: test-deu.firstdomain.com
    '*.service.geo.firstdomain.com':
      - cname: test-jpn.firstdomain.com
  services:
    test.geo.firstdomain.com: '%co.service.geo.firstdomain.com'
- domain: geo.seconddomain.com
  ttl: 3600
  records:
    geo.seconddomain.com:
      - soa: ns1.seconddomain.com hostmaster.seconddomain.com 2016020302 7200 900 3600000 300
      - ns: ns1.seconddomain.com
      - ns: ns2.seconddomain.com
      - mx: 10 mx.seconddomain.com
    deu.service.geo.seconddomain.com:
      - cname: test-deu.seconddomain.com
    '*.service.geo.seconddomain.com':
      - cname: test-jpn.seconddomain.com
  services:
    test.geo.seconddomain.com: '%co.service.geo.seconddomain.com'
```
With this configuration requests for  test.geo.firstdomain.com work as expected.
But requests for test.geo.seconddomain.com or any other RR of geo.seconddomain.com gives no result.

Why cant we have a second/third/... geo domain in the GeoIP backend? Am I doing something wrong or is this a bug? Or is this only not supported currently?
