### ISSUE TITLE
GeoIP fails to answer for services apparently when there is another service that is a subdomain of that service.

### ISSUE THREAD

**Issue by mooinglemur** [PowerDNS/pdns#3747]
In the example below, the geoip backend will properly serve answers for queries for `sub.service.example.com` but simply return the SOA when you query `service.example.com`

A workaround that works seems to be renaming `service.example.com` to something like `service1.example.com` and then placing a `service.example.com` in the records section as a CNAME, pointing to `service1.example.com`

```
  - domain: example.com
    ttl: 300
    records:
        example.com:
          - soa: ns1.example.com hostmaster.example.com 2014090125 7200 3600 1209600 3600
          - ns: ns1.example.com
        '*.an.geo.example.com':
          - a: 127.0.0.1
        '*.af.geo.example.com':
          - a: 127.0.0.2
        '*.as.geo.example.com':
          - a: 127.0.0.3
        '*.eu.geo.example.com':
          - a: 127.0.0.4
        '*.na.geo.example.com':
          - a: 127.0.0.5
        '*.oc.geo.example.com':
          - a: 127.0.0.6
        '*.sa.geo.example.com':
          - a: 127.0.0.7
        '*.an.sub.geo.example.com':
          - a: 127.0.0.1
        '*.af.sub.geo.example.com':
          - a: 127.0.0.2
        '*.as.sub.geo.example.com':
          - a: 127.0.0.3
        '*.eu.sub.geo.example.com':
          - a: 127.0.0.4
        '*.na.sub.geo.example.com':
          - a: 127.0.0.5
        '*.oc.sub.geo.example.com':
          - a: 127.0.0.6
        '*.sa.sub.geo.example.com':
          - a: 127.0.0.7
    services:
      service.example.com: '%co.%cn.geo.example.com'
      sub.service.example.com: '%co.%cn.sub.geo.example.com'
```

**Comment by pieterlexis** [comment]
for completeness, can you comment with the version of PowerDNS, the OS you run this on and the `pdns.conf`?

**Comment by mooinglemur** [comment]
This was compiled from this github repo sources on Gentoo via a live ebuild that I constructed, no patches or other modifications.

```
Apr 26 21:34:42 PowerDNS Authoritative Server 0.0.g29115b8 (C) 2001-2016 PowerDNS.COM BV
Apr 26 21:34:42 Using 64-bits mode. Built using gcc 4.9.3 on Apr 19 2016 22:12:32 by portage@nsx-ng.
Apr 26 21:34:42 PowerDNS comes with ABSOLUTELY NO WARRANTY. This is free software, and you are welcome to redistribute it according to the terms of the GPL version 2.
Apr 26 21:34:42 Features: openssl 
Apr 26 21:34:42 Built-in modules: 
Apr 26 21:34:42 Configured with: " '--prefix=/usr' '--build=x86_64-pc-linux-gnu' '--host=x86_64-pc-linux-gnu' '--mandir=/usr/share/man' '--infodir=/usr/share/info' '--datadir=/usr/share' '--sysconfdir=/etc' '--localstatedir=/var/lib' '--disable-dependency-tracking' '--disable-silent-rules' '--sysconfdir=/etc/powerdns' '--libdir=/usr/lib64/powerdns' '--with-modules=' '--with-dynmodules=pipe bind tinydns geoip' '--with-pgsql-includes=/usr/include' '--with-pgsql-lib=/usr/lib64' '--with-mysql-lib=/usr/lib64' '--disable-unit-tests' '--without-lua' '--disable-static-binaries' '--disable-tools' 'build_alias=x86_64-pc-linux-gnu' 'host_alias=x86_64-pc-linux-gnu' 'CFLAGS=-O2 -pipe' 'LDFLAGS=-Wl,-O1 -Wl,--as-needed' 'CXXFLAGS=-O2 -pipe' 'PKG_CONFIG_PATH=/usr/lib64/pkgconfig'"
```

Comments have been omitted and our public IPs have been redacted
```
allow-recursion=[redacted]/27 [redacted]/27 127.0.0.0/8
edns-subnet-processing=yes
launch=tinydns,geoip
local-address=[redacted (30 addresses)]
local-address-nonexist-fail=no
local-ipv6=[redacted (30 addresses)]
local-ipv6-nonexist-fail=no
log-dns-queries=yes
logging-facility=7
loglevel=9
recursor=[redacted]
reuseport=yes
setgid=pdns
setuid=pdns
tinydns-dbfile=/home/dnsgit/tinydns-root/data.cdb
geoip-zones-file=/home/dnsgit/geoipdns-root/zones.yaml
geoip-database-files=/usr/share/GeoIP/GeoIP.dat /usr/share/GeoIP/GeoIPv6.dat
```

**Comment by cmouse** [comment]
Can you provide sample queries done with dig?

**Comment by urusha** [comment]
I had the same issue with debian 9, amd64, 4.0.3.
Even more, I can not use geo for root record `example.com`
With this config:
```
domains:
- domain: example.com
  ttl: 300
  records:
    ns1.example.com:
      - a: 127.0.0.3
    ns2.example.com:
      - a: 127.0.0.2
    mail.example.com:
      - a: 127.0.0.3
    example.com:
      - soa: ns1.example.com hostmaster.example.com 123 7200 3600 1209600 3600
    root.default.geo.example.com:
      - soa: ns1.example.com hostmaster.example.com 123 7200 3600 1209600 3600
      - ns: ns1.example.com
      - ns: ns2.example.com
      - mx: 10 mail.example.com
      - a: 127.0.0.2
    root.eu.geo.example.com:
      - soa: ns1.example.com hostmaster.example.com 123 7200 3600 1209600 3600
      - ns: ns1.example.com
      - ns: ns2.example.com
      - mx: 10 mail.example.com
      - a: 127.0.0.3
    default.geo.example.com:
      - a: 127.0.0.2
    eu.geo.example.com:
      - a: 127.0.0.3
  services:
    example.com: ['root.%cn.geo.example.com', 'root.default.geo.example.com']
    "*.example.com": ['%cn.geo.example.com', 'default.geo.example.com']
```
I get no geo (see no mx,a records):
```
# dig @127.0.0.2 example.com

; <<>> DiG 9.10.3-P4-Debian <<>> @127.0.0.2 example.com
; (1 server found)
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 48052
;; flags: qr aa rd; QUERY: 1, ANSWER: 0, AUTHORITY: 1, ADDITIONAL: 1
;; WARNING: recursion requested but not available

;; OPT PSEUDOSECTION:
; EDNS: version: 0, flags:; udp: 1680
;; QUESTION SECTION:
;example.com.			IN	A

;; AUTHORITY SECTION:
example.com.		300	IN	SOA	ns1.example.com. hostmaster.example.com. 123 7200 3600 1209600 3600

;; Query time: 0 msec
;; SERVER: 127.0.0.2#53(127.0.0.2)
;; WHEN: Fri Jul 21 12:24:41 UTC 2017
;; MSG SIZE  rcvd: 91
```
With this:
```
domains:
- domain: example.com
  ttl: 300
  records:
    ns1.example.com:
      - a: 127.0.0.3
    ns2.example.com:
      - a: 127.0.0.2
    mail.example.com:
      - a: 127.0.0.3

#    example.com:
#      - soa: ns1.example.com hostmaster.example.com 123 7200 3600 1209600 3600

    root.default.geo.example.com:
      - soa: ns1.example.com hostmaster.example.com 123 7200 3600 1209600 3600
      - ns: ns1.example.com
      - ns: ns2.example.com
      - mx: 10 mail.example.com
      - a: 127.0.0.2

    root.eu.geo.example.com:
      - soa: ns1.example.com hostmaster.example.com 123 7200 3600 1209600 3600
      - ns: ns1.example.com
      - ns: ns2.example.com
      - mx: 10 mail.example.com
      - a: 127.0.0.3

    default.geo.example.com:
      - a: 127.0.0.2
    eu.geo.example.com:
      - a: 127.0.0.3

  services:
    example.com: ['root.%cn.geo.example.com', 'root.default.geo.example.com']
    "*.example.com": ['%cn.geo.example.com', 'default.geo.example.com']
```
I get no answer at all (seems because pdns expects that the root record exists )
```
# dig @127.0.0.2 example.com

; <<>> DiG 9.10.3-P4-Debian <<>> @127.0.0.2 example.com
; (1 server found)
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: REFUSED, id: 17716
;; flags: qr rd; QUERY: 1, ANSWER: 0, AUTHORITY: 0, ADDITIONAL: 1
;; WARNING: recursion requested but not available

;; OPT PSEUDOSECTION:
; EDNS: version: 0, flags:; udp: 1680
;; QUESTION SECTION:
;example.com.			IN	A

;; Query time: 0 msec
;; SERVER: 127.0.0.2#53(127.0.0.2)
;; WHEN: Fri Jul 21 12:25:58 UTC 2017
;; MSG SIZE  rcvd: 40
```
