### ISSUE TITLE
Is that possible to set a GEODNS for root domain when using GeoIP backend?

### ISSUE THREAD

**Issue by ZE3kr** [PowerDNS/pdns#4276]
I want to use GEODNS to my root domain, but it doesn't work.

First, i tried this, and works for www domain:

``` yaml
# config 1 file
- domain: example.com
  ttl: 1800
  records:
    example.com:
      - soa: ns1.example.com. support.example.com. 1 86400 3600 604800 10800
    ns1.example.com:
      - a:
          content: 10.0.0.1
          ttl: 86400
      - aaaa:
          content: ::1
          ttl: 86400
    ns2.example.com:
      - a:
          content: 10.0.0.2
          ttl: 86400
      - aaaa:
          content: ::2
          ttl: 86400
    # just a list of servers
    newyork-server.example.com: &newyork
      - a: 10.0.2.1
      - aaaa: ::2:1
    japan-server.example.com: &japan
      - a: 10.0.3.1
      - aaaa: ::3:1
    # GEODNS
    unknown.geo.example.com: *newyork
    as.geo.example.com: *japan
  services:
    www.example.com: [ '%cn.geo.example.com', 'unknown.geo.example.com' ]
```

And I change `www.example.com` to `example.com`, it does't work, I think it is because I set same domain in record and service. The dig return only SOA record for my root domain, but no A and AAAA.

``` bash
# result 1
$ dig @localhost example.com

; <<>> DiG 9.10.3-P4-Ubuntu <<>> @localhost example.com
; (1 server found)
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 1041
;; flags: qr aa rd; QUERY: 1, ANSWER: 0, AUTHORITY: 1, ADDITIONAL: 1
;; WARNING: recursion requested but not available

;; OPT PSEUDOSECTION:
; EDNS: version: 0, flags:; udp: 1680
;; QUESTION SECTION:
;example.com.           IN  A

;; AUTHORITY SECTION:
example.com.        1800    IN  SOA ns1.example.com. support.example.com. 1 86400 3600 604800 10800

;; Query time: 1 msec
;; SERVER: 127.0.0.1#53(127.0.0.1)
;; WHEN: Tue Aug 02 19:37:26 EDT 2016
;; MSG SIZE  rcvd: 88
```

Then I tried this config file:

``` yaml
# config 3 file
- domain: example.com
  ttl: 1800
  records:
    ns1.example.com:
      - a:
          content: 10.0.0.1
          ttl: 86400
      - aaaa:
          content: ::1
          ttl: 86400
    ns2.example.com:
      - a:
          content: 10.0.0.2
          ttl: 86400
      - aaaa:
          content: ::2
          ttl: 86400
    # just a list of servers
    unknown.geo.example.com:
      - a: 10.0.2.1
      - aaaa: ::2:1
      - soa: ns1.example.com. support.example.com. 1 86400 3600 604800 10800
    as.geo.example.com:
      - a: 10.0.3.1
      - aaaa: ::3:1
      - soa: ns1.example.com. support.example.com. 1 86400 3600 604800 10800
  services:
    example.com: [ '%cn.geo.example.com', 'unknown.geo.example.com' ]
```

It really works well, but when I re-add this to services block, suddenly the root domain returns nothing (just like result 1) but only www domain works!

``` yaml
  services:
    example.com: [ '%cn.geo.example.com', 'unknown.geo.example.com' ]
    www.example.com: [ '%cn.geo.example.com', 'unknown.geo.example.com' ]
```

I think it's a bug because https://github.com/PowerDNS/pdns/issues/3747 , and also please add extra support so that I can set it up easily by config 1 file.
