### ISSUE TITLE
Geoip weights functionality ignored during processing geoip found records

### ISSUE THREAD

**Issue by meteozond** [PowerDNS/pdns#4704]
We are deploying 4.0.1-1pdns.jessie geoip+mysql backed pdns-server, and found some inconvenience in geoip weights functionality and documentation.  

Looks like weights support and documentation are not consistent. Weights only works for 
statically defined records, but if record was found (or unknown taken) through the geoip 
services section or (alternative syntax) weights are completely ignored.

Weights sould work for geoip found records as for static.

This configuration will return all A records for domain geo.example.com:

```
domains:
- domain: example.com
  ttl: 30
  records:
    unknown.unknown.geo.example.com:
      - a:
           content: 10.0.0.2
           weight: 500
      - a:
           content: 10.0.0.1
           weight: 500
  services:
    geo.zerocdn.com:
      default: [ '%ci.%co.geo.example.com']
```
  
Possible workaround is in using some CNAME proxy record, but it is not documented:

```
domains:
- domain: example.com
  ttl: 30
  records:
    unknown.unknown.geo.example.com:
      - a:
           content: 10.0.0.2
           weight: 500
      - a:
           content: 10.0.0.1
           weight: 500
    unknown.unknown.proxy.geo.example.com:
      - cname: unknown.unknown.geo.example.com
  services:
    geo.zerocdn.com:
      default: [ '%ci.%co.proxy.geo.example.com']
```
