### ISSUE TITLE
%re doesn't work with the geoip backend

### ISSUE THREAD

**Issue by blauwblaatje** [PowerDNS/pdns#5255]
- Program: Authoritative
 - Issue type: Bug report 

### Short description
Region code in GeoIP backend doesn't seem to work.  

### Environment
 - Operating system: Debian
 - Software version:  pdns-backend-geoip                   4.0.3-1pdns.jessie, pdns-server                          4.0.3-1pdns.jessie
 - Software source: Pdns debian repo

### Steps to reproduce
1.  MM GeoLite City database. This one has Region_code:

```
In [3]: print geo.record_by_addr('107.170.203.71')
{'city': u'San Francisco', 'region_code': u'CA', 'area_code': 415, 'time_zone': 'America/Los_Angeles', 'dma_code': 807, 'metro_code': 'San Francisco, CA', 'country_code3': 'USA', 'latitude': 37.735299999999995, 'postal_code': u'94124', 'longitude': -122.3732, 'country_code': 'US', 'country_name': 'United States', 'continent': 'NA'}
```

2. PDNS GeoIP backend
*snip*

```
     ca.mirror.global.i3d.net:
       - a: 162.244.52.45
       - txt: LAX
     eu.mirror.global.i3d.net:
       - a: 213.163.76.200
       - txt: RTM
    services:
       mirror.global.i3d.net:
         default: [ '%re.mirror.global.i3d.net', 'eu.mirror.global.i3d.net' ]
 
```

3. Ask dns server for record
```
rogier@kishu:~$ ip a sh eth0 |grep inet
    inet 107.170.203.71/20 brd 107.170.207.255 scope global eth0
rogier@kishu:~$ dig mirror.global.i3d.net @213.163.76.133 -t TXT +short
"RTM"
rogier@kishu:~$ dig mirror.global.i3d.net @213.163.76.133 +short
213.163.76.200
```

### Expected behaviour
I would expect that %re.mirror.global.i3d.net would return the entry for ca.mirror.global.i3d.net.

### Actual behaviour
See step three. In stead of %re resolving, the fallback option is taken, so you get the entry of eu.mirror.global.i3d.net.   If I leave out the fallback option, I get an empty response.  So my conclusion is that %re doesn't resolve. 

### Other information
 I've tried %cn and %co and respectively NA or USA and that worked perfectly.
