### ISSUE TITLE
Out of range exception parsing

### ISSUE THREAD

**Issue by qxrftz** [PowerDNS/pdns#5984]
- Program: Authoritative
 - Issue type: Bug report

### Short description
Backend reported permanent error which prevented lookup (Out of range exception parsing ns1.oa.com root.oa.com 20171122220534 60 30 604800 3602), aborting

### Environment
 - Operating system:  CentOS6.9
 - Software version: pdns-4.1.0-0.1.rc3.1pdns.el6.x86_64
 - Software source: PowerDNS repository

### Steps to reproduce
1. start server
2. request to server

### Usecase
here is my geoip zone file:
```
domains:
- domain: oa.com
  records:
    BK.mail.oa.com:
    - A:
        content: 172.21.0.1
        weight: 100
    KX.mail.oa.com:
    - A:
        content: 172.18.0.1
        weight: 100
    - A:
        content: 172.18.0.2
        weight: 50
    KX.ns1.oa.com:
    - A:
        content: 4.4.4.4
        weight: 100
    default.mail.oa.com:
    - A:
        content: 172.28.0.1
        weight: 100
    default.www.oa.com:
    - A:
        content: 1.1.1.1
        weight: 100
    oa.com:
    - soa: ns1.oa.com root.oa.com 20171122220534 60 30 604800 3602
    - MX:
        content: mail.oa.com
        weight: 100
    - NS:
        content: ns1.oa.com
        weight: 100
  services:
    mail.oa.com:
      0.0.0.0/0: default.mail.oa.com
      172.18.0.0/16: KX.mail.oa.com
      172.21.0.0/16: BK.mail.oa.com
    ns1.oa.com:
      172.18.0.0/16: KX.ns1.oa.com
    www.oa.com:
      0.0.0.0/0: default.www.oa.com
  ttl: 3600
```

### Description
Can anybody tell me what's wrong with the zone file?
by the way, how can I get more detail debug information?
