### ISSUE TITLE
How to set NS/MX... records at zone apex?

### ISSUE THREAD

**Issue by qxrftz** [PowerDNS/pdns#5985]
- Program: Authoritative
 - Issue type: Bug report

### Short description
1. pdnsutil check-zone always shows a '[Error] No NS record at zone apex in zone' error
2. dns client got nothing after server start for several minutes.

### Environment
 - Operating system: CentOS6.9
 - Software version: pdns-4.1.0-0.1.rc3.1pdns.el6.x86_64
 - Software source: PowerDNS repository

### Usecase
here is my zone file:
```
domains:
- domain: oa.com
  records:
    default.www.oa.com:
    - A:
        content: 1.1.1.1
        weight: 100
    oa.com:
    - soa: ns1.oa.com root.oa.com 2017112202 60 30 604800 3602
    - ns: ns1.oa.com
    - mx: mail.oa.com
  services:
    www.oa.com:
      0.0.0.0/0: default.www.oa.com
  ttl: 3600
```

### Description
Error 2 I mentioned can be fixed by removing the ns and mx record in my zone file, but I don't know what's wrong with it and the server log shows no error.

Can anybody show the right syntax?
