### ISSUE TITLE
GeoIP and DNSSEC with ALIAS

### ISSUE THREAD

**Issue by qarizma** [PowerDNS/pdns#6619]
- Program: Authoritative
 - Issue type: Bug report

### Short description
First of all, great job with the GeoIP module, it works like a charm. I like the way it works with a yaml file (would be nice to support multiple yaml files for each domain though).

About 6 hours ago I successfully setup PowerDNS with GeoIP backend, it fully worked including DNSSEC on the ROOT domain. Resulting in a working GeoDNS solution on domain.com with DNSSEC enabled. All these hours the zone was working correctly. Suddenly after about 6 hours the zone stopped functioning correctly.

### Environment
 - Operating system: CentOS 7.5.1804 (3.10.0-514.el7.x86_64)
 - Software version: 4.1.2
 - Software source: PowerDNS repository

### Steps to reproduce
1. Simply install pdns and the geoip backend.
2. Apply the provided configs.
3. Do a dig on the root domain.

### Expected behaviour
Well, I'm not 100% sure if my setup is supposed to work. However it worked for a while. Now I'm investigating and wondering why it even worked (if it shouldn't work) and why it stopped working.
I would expect a correct A record returned based on my location, at the root of the domain.com, with DNSSEC enabled.

### Actual behaviour
DNSviz returns the following error: No RRSIG covering the RRset was returned in the response (Record Type: A, Status: BOGUS).
Dig returns an empty A record.

### Other information
I have created a service (geoip.domain.com) and then created an ALIAS on the root pointing to the service. This worked for a while. Is there an explanation why this worked a few hours?

pdns.conf:
```
launch=geoip
geoip-database-files=/usr/share/GeoIP/GeoIP.dat,/usr/share/GeoIP/GeoIPv6.dat
geoip-zones-file=/etc/pdns/zone.yaml
geoip-dnssec-keydir=/etc/pdns/dnssec
expand-alias=yes
```

zone.yaml:
```
domains:
- domain: domain.com
  ttl: 60
  records:
    domain.com:
      - soa: ns1.domain.com hostmaster.domain.com 2018051600 3600 7200 1209600 86400
      - ns: ns1.domain.com
      - ns: ns2.domain.com
      - alias: geoip.domain.com
    ns1.domain.com:
      - a: 127.0.0.1
    ns2.domain.com:
      - a: 127.0.0.2
    eu.service.geoip.domain.com:
      - a: 192.168.0.7
    nl.service.geoip.domain.com:
      - a: 192.168.88.88
    a.domain.com:
      - a:
          content: 0.0.0.0
          ttl: 90
    aaaa.domain.com:
      - aaaa:
          content: 2001:4860:4860::8888
          ttl: 120
  services:
    geoip.domain.com: ['%cc.service.geoip.domain.com', '%cn.service.geoip.domain.com']
```

Some facts:
- DNSSEC **is** successfully configured, confirmed by DNSviz (and human validation).
- GeoDNS on the root domain.com (using ALIAS) work**ed** flawlessly, confirmed using https://dnschecker.org.
- geoip.domain.com is still working, only the root domain.com stopped working.
- Removing the ALIAS entry and adding an A entry makes the zone working again, as expected.
- I was using Google DNS (8.8.8.8) as my resolvers all the time.

Thank you for your time and help.

**Comment by rgacogne** [comment]
Could you post the complete outputs (and commands when relevant) of dnsviz and dig, both when it works and when it doesn't?

**Comment by qarizma** [comment]
```
domains:
- domain: domain.com
  ttl: 60
  records:
    domain.com:
      - soa: ns1.domain.com hostmaster.domain.com 2018051600 3600 7200 1209600 86400
      - ns: ns1.domain.com
      - ns: ns2.domain.com
      - aaaa: 2001:4860:4860::8888
    ns1.domain.com:
      - a: 127.0.0.1
    ns2.domain.com:
      - a: 127.0.0.2
    unknown.service.geoip.domain.com:
      - a: 192.168.0.0
    na.service.geoip.domain.com:
      - a: 192.168.0.4
    sa.service.geoip.domain.com:
      - a: 192.168.0.5
    as.service.geoip.domain.com:
      - a: 192.168.0.6
    eu.service.geoip.domain.com:
      - a: 192.168.0.7
    nl.service.geoip.domain.com:
      - a: 192.168.88.88
    a.domain.com:
      - a:
          content: 0.0.0.0
          ttl: 90
    aaaa.domain.com:
      - aaaa:
          content: 2001:4860:4860::8888
          ttl: 120
  services:
    geoip.domain.com: ['%cc.service.geoip.domain.com', '%cn.service.geoip.domain.com', 'unknown.service.geoip.domain.com']
    domain.com: ['%cc.service.geoip.domain.com', '%cn.service.geoip.domain.com', 'unknown.service.geoip.domain.com']
```

I made some changes to the zone file, and it seems it started working again. I accidentally removed the last service line: domain.com. Removed the ALIAS record in root and restarted.

Still doing some investigation now, just to be sure if this is the cause.
