### ISSUE TITLE
How do I check the configuration before restarting the powerdns service ?

### ISSUE THREAD

**Issue by xuxiaomo** [PowerDNS/pdns#6791]
- Program: Authoritative
- Issue type: Feature request

### Short description
Check config file is valid

### Usecase
Check files like nginx -t

### Description
I am using the geoip backend of powerdns to manage my domain name, This is managed through a front-end and automatically generates *zones.yaml* config file<br>
whether there is a way to check the validity of the configuration before restart the service (the validity refers to the configuration file grammatical errors, rather than semantic error), to prevent incorrect configuration service downtime

**Comment by zeha** [comment]
Auth supports `--config=check` since 4.3.0.

**Comment by whitepiratebaku** [comment]
cant find documentation related to configuration checking, can you explain how it works?

**Comment by M0NsTeRRR** [comment]
It would be better if we had a separate option like for nginx with `-t` flag. My use case is with ansible and template module.

```yaml
- name: Configure PowerDNS authoritative
  ansible.builtin.template:
    src: pdns.conf.j2
    dest: /etc/powerdns/pdns.conf
    owner: "pdns"
    group: "pdns"
    mode: "0640"
  validate: /usr/sbin/pdns_server --config %s
  notify: Restart pdns
```

`validate` is the command to run before copying the updated file into the final destination.
