### ISSUE TITLE
Conn closed: TLS - *Failure*`

### ISSUE THREAD

**Issue by Warok21** [PowerDNS/pdns#7276]
- Program: dnsdist
- Issue type: Failure

### Short description
Environment
- Operating system: Ubuntu 16.04
- Software version: dnsdist 1.3.3 (Lua 5.1.4)
### Steps to reproduce

$ openssl req -newkey rsa:2048 -nodes -keyout dnsdist.key -x509 -days 365 -out dnsdist.pem
$ openssl rsa -pubout -outform der -in dnsdist.key | openssl dgst -binary -sha256 | openssl base64  #used to compute the hash for stubby

```
cat /etc/dnsdist/dnsdist.conf 
addLocal("127.0.0.1")
addTLSLocal('127.0.0.1', '/home/adriano/projet/dnsdist.pem', '/home/adriano/projet/dnsdist.key')
newServer({address='130.59.31.248:853'})

```
### Client : 
Windows 10
Content of stubby.yml:
```
resolution_type: GETDNS_RESOLUTION_STUB
dns_transport_list:
  - GETDNS_TRANSPORT_TLS
tls_authentication: GETDNS_AUTHENTICATION_REQUIRED
tls_query_padding_blocksize: 128
edns_client_subnet_private : 1
round_robin_upstreams: 1
idle_timeout: 10000
listen_addresses:
  - 127.0.0.1
  - 0::1
upstream_recursive_servers:
  - address_data: 160.98.31.165
    tls_auth_name: "cn that I used in the command"
    tls_pubkey_pinset:
      - digest: "sha256"
        value: computed hash
```

### Expected behaviour
Client making the connection with the server
### Actual behaviour
Copy paste from the console of stubby : 
`160.98.31.165                            : Conn closed: TLS - *Failure*`
### Details
160.98.30.134 is my client and 160.98.31.165 is my server and here is the what wireshark get:
[Packets](https://imgur.com/a/kTn6GzA)
