### ISSUE TITLE
ifurlup health check in LUA records does not use User-Agent

### ISSUE THREAD

**Issue by splk3** [PowerDNS/pdns#7393]
- Program: Authoritative
 - Issue type: Bug report

### Short description
When using LUA records with PowerDNS Authoritative Server, health checks to URLs do not include a User-Agent in the request.  This causes some webservers/applications to heavily rate-limit or outright block (http code 403 forbidden) the requests to those URLs, effectively marking the resource DOWN permanently.  

PowerDNS should include an appropriate User-Agent configuration, or allow one to be set in the function or pdns.conf file.

### Environment
 - Operating system: CentOS 7
 - Software version: 4.2.0alpha 
Jan 18 16:19:39 PowerDNS Authoritative Server 0.0.15853.0.gf5c3a56e81 (C) 2001-2019 PowerDNS.COM BV
geoip backend version 0.0.15853.0.gf5c3a56e81 (Jan 17 2019 19:36:53)
 - Software source: PowerDNS repository (master)
 - Back End Server(s): apache web servers with modsecurity (or another back-end with protocol filtering enabled that requires a User-Agent specified in requests)

```
# /etc/pdns/pdns.conf
config-dir=/etc/pdns
setuid=pdns
setgid=pdns
cache-ttl=0
disable-syslog=no
edns-subnet-processing=yes
enable-lua-records=yes
local-address=192.168.137.252
local-port=53
log-dns-queries=yes
loglevel=6
master=yes
negquery-cache-ttl=0
query-cache-ttl=0
receiver-threads=2
slave=no

launch=

launch+=geoip
geoip-database-files=/usr/share/GeoIP/GeoLite2-Country.mmdb
geoip-zones-file=/opt/pdns/zonefile.yml
```

```
# /opt/pdns/zonefile.yml
---
domains:
  - domain: gslb.lab.lan
    ttl: 30
    records:
      gslb.lab.lan:
        - soa: gslb.lab.lan admin.lab.lan 1 30 30 30 1
        - ns: pdns-gslb-centos-7.lab.lan 
        - a: 192.168.137.252 
      test.gslb.lab.lan:
        - lua: 'a "ifurlup(''''https://test.lab.lan'''', 
        {''''192.168.84.204'''', ''''192.168.128.21''''})"'
```

### Steps to reproduce
1. Configure basic entry for PowerDNS and GeoIP back end similar to above
2. Do a query of the gslb'd domain to the server
3. Watch logs in /var/log/messages to see UP/DOWN status of back-ends

### Expected behaviour
Health checks succeed/fail based on the availability of the resource at the IPs/URL specified in the LUA record.

If User-Agent is not defined by default, a configuration file entry could specify a specific User-Agent for the process.

### Actual behaviour
modsecurity on the webservers blocked the health checks because of a lack of "User-Agent" being specified by the health check request.  See below for log entry info from web server.

### Other information
Excerpt from example log entry from modsecurity included below:
```
Jan 18 10:19:26 ... ModSecurity: Access denied with code 403 (phase 2). Operator EQ matched 0 at REQUEST_HEADERS. [file ".../modsecurity.d/activated_rules/modsecurity_crs_21_protocol_anomalies.conf"] [line "66"] [id "960009"] 
[rev "1"] [msg "Request Missing a User Agent Header"] [severity "NOTICE"] [ver "OWASP_CRS/2.2.9"]
 [maturity "9"] [accuracy "9"] [tag "OWASP_CRS/PROTOCOL_VIOLATION/MISSING_HEADER_UA"]
 [tag "WASCTC/WASC-21"] [tag "OWASP_TOP_10/A7"] [tag "PCI/6.5.10"] [hostname "test.lab.lan"] 
[uri "/"] [unique_id "XEHufulCfZ0ennrlKawnvgAAAc8"] 
```
