### ISSUE TITLE
GeoDNS subdomain issue

### ISSUE THREAD

**Issue by csanszan1** [PowerDNS/pdns#8384]
Hey,

I'm createing a geoDNS with PowerDNS, but instead of creating a per country response, it creates a subdomain, e.g *.eu.cdn.example.net is a subdomain, and cdn.example.net is not exist.
Zone config:
```
domains:
- domain: acsanad.net
  ttl: 120
  records:
    exapmle.net:
      - soa: ns1.exaple.net hostmaster.example.net 201006601 7200 3600 1209600 3600
      - ns:
           content: ns1.example.net
           ttl: 120
      - ns: ns2.example.net
      - mx: 10 mail.example.eu
      - a: 185.33.***.**
    ns1.example.net:
      - a: 185.185.***.**
    ns2.example.net:
      - a: 185.33.***.**
    '*.eu.cdn.example.net':
      - a: 185.33.***.**
      - txt: DEU
    '*.as.cdn.example.net':
      - a: 81.2.***.**
      - txt: ASIA
    '*.na.cdn.example.net':
      - txt: Norh America
      - a: 81.2.***.**
    '*.cdn.example.net':
      - txt: Other
      - a: 81.2.***.**
```
