### ISSUE TITLE
geoip service for apex domain does not resolve

### ISSUE THREAD

**Issue by poidl** [PowerDNS/pdns#9341]
I'm a beginner and I'm trying to resolve the root domain 'example.com' to different ips depending from which continent the query comes.

I read this
https://doc.powerdns.com/authoritative/backends/geoip.html
but I can't get it to work. Below I link to a thread where a user did precisely (?) what I want to do, but in my case it doesn't work.

Version: 4.2.2
Where you got the software from: Arch Linux package
Steps to reproduce:
According to the old thread linked below, I thought this would work:
```
domains:
- domain: example.com
  ttl: 30
  records:
    ns01.example.com:
      - a: 192.0.2.1
    eu.example.com:
      - a: 192.0.2.1
      - ns: ns01.example.com
      - soa: ns01.example.com admin.example.com 2 10380 3600 604800 3600
    as.example.com:
      - a: 192.0.2.2
      - ns: ns01.example.com
      - soa: ns01.example.com admin.example.com 2 10380 3600 604800 3600
  services:
    example.com: [ '%cn.example.com' ]
```
but there is no ANSWER SECTION in the dig output for 'example.com'
Using
```
domains:
- domain: example.com
  ttl: 30
  records:
    example.com:
      - ns: ns01.example.com
      - soa: ns01.example.com admin.example.com 2 10380 3600 604800 3600
    ns01.example.com:
      - a: 192.0.2.1
    eu.example.com:
      - a: 192.0.2.1
    as.example.com:
      - a: 192.0.2.2
  services:
    www.example.com: [ '%cn.example.com' ]
```
and querying 'www.example.com' from Europe yields, as expected:
```
;; ANSWER SECTION:
www.example.com.        30      IN      A       192.0.2.1
```
and from Tokio I get 192.0.2.2.
But removing the `www.` in the service name will yield the following:
```
Cannot have static record and CNAME at the same time.Please fix your configuration for "example.com", so that it can be resolved by GeoIP backend directly.
```
The error message makes sense, but doesn't give a hint on how I would fix it. Do I need an ALIAS record?

I read these old threads:

https://github.com/PowerDNS/pdns/issues/4276#issue-169015162

and I think what I want to do should work in the current version. There is one post in the thread where they have something identical to my first try above, and they say it worked.

Thanks a lot for your help.
