### ISSUE TITLE
Zone registered to GeoIP backend will be resolv incorrectly in Generic MySQL backend. 

### ISSUE THREAD

**Issue by hunter9x** [PowerDNS/pdns#9373]
- Program: Authoritative 
 - Issue type: Bug report

### Short description

Zone registered to GeoIP backend will be resolv incorrectly in Generic MySQL backend. 

### Environment

 - Operating system: Ubuntu 18.04
 - Software version: PowerDNS Authoritative Server 4.1.13
 - Software source: 

### Steps to reproduce

1. create zone and a A record in MySQL 
2. create configuration in geoip-zones-file for same zone

### Expected behaviour

A record resolving response NOERROR

### Actual behaviour

A record resolving response NXDOMAIN

### Other information

For example, i have `example.com` zone in database like below.

```
select domain_id, name, type, content, ttl, prio  from recordsr where name = 'example.com' and type = 'NS';
+-----------+-------------+------+-----------------------+------+------+
| domain_id | name        | type | content               | ttl  | prio |
+-----------+-------------+------+-----------------------+------+------+
|      5377 | example.com | NS   | primary.nameserver    | 3600 | NULL |
|      5377 | example.com | NS   | secondary.nameserver  | 3600 | NULL |
+-----------+-------------+------+-----------------------+------+------+
```

```
select domain_id, name, type, content, ttl, prio  from records where name = 'foo.example.com';
+-----------+---------------------+------+---------+------+------+
| domain_id | name                | type | content | ttl  | prio |
+-----------+---------------------+------+---------+------+------+
|      5377 | foo.example.com     | A    | 1.1.1.1 |   60 | NULL |
+-----------+---------------------+------+---------+------+------+
```

I also have configruration for `example.com` in `geoip-zones-file` like below.

```
---
domains:
- domain: example.com
  ttl: 3600
  records:
    example.com:
    - soa: primary.nameserver hostmaster xxxx
    as.geoip.example.com
    - a: 1.1.1.1
    na.geoip.example.com
    - a: 2.2.2.2
    default.geoip.example.com
    - a: 3.3.3.3
  services:
    geoip.example.com:
    - "%cn.geoip.example.com"
    - default.geoip.example.com
```

GeoIP backend works well, `dig geoip.example.com` resulted as i expected. But the when i try to `dig foo.example.com` the response was NXDOMAIN. 
I enabled MySQL general log and founded that in `dig foo.example.com` the value of `domain_id` was `0` and maybe it caused the problem. 

```
Prepare   select content,ttl,prio,type,domain_id,false,name,true from records where type=? and name=?
Execute   select content,ttl,prio,type,domain_id,false,name,true from records where type='SOA' and name='example.com'
Reset stmt
Prepare   select content,ttl,prio,type,domain_id,false,name,true from records where type=? and name=? and domain_id=?
Execute   select content,ttl,prio,type,domain_id,false,name,true from records where type='NS' and name='example.com' and domain_id=0
Reset stmt
Prepare   select content from domains, domainmetadata where domainmetadata.domain_id=domains.id and name=? and domainmetadata.kind=?
Execute   select content from domains, domainmetadata where domainmetadata.domain_id=domains.id and name='example.com' and domainmetadata.kind='ENABLE-LUA-RECORDS'
Reset stmt
Prepare   select content,ttl,prio,type,domain_id,false,name,true from records where name=? and domain_id=?
Execute   select content,ttl,prio,type,domain_id,false,name,true from records where name='example.com' and domain_id=0
Reset stmt
Execute   select content,ttl,prio,type,domain_id,false,name,true from records where name='*.example.com' and domain_id=0
Reset stmt
Execute   select content from domains, domainmetadata where domainmetadata.domain_id=domains.id and name='example.com' and domainmetadata.kind='SOA-EDIT'
Reset stmt
```

`0` maybe is the order number of `example.com` in `geoip-zones-file`. When turned off GeoIP backend and try to `dig foo.example.com` again the problem was resolved.
BTW, i tested in `4.1.13` `4.2.2` `4.3.0`

**Comment by Habbie** [comment]
As your geoip config only has names under geoip.example.com, I suggest changing the zonename to that as well. Make sure to put a delegation in the gmysql example.com zone.

**Comment by hunter9x** [comment]
Hi Habbie. Thank you for the quick answer.
As your suggestion it worked !

BTW, how about when i have to write multiple services under one zone ?
In fact, i plant to use GeoIP backend in this way.

```
---
domains:
- domain: example.com
  ttl: 3600
  records:
    example.com:
    - soa: primary.nameserver hostmaster xxxx
    as.geoip.example.com
    - a: 1.1.1.1
    na.geoip.example.com
    - a: 2.2.2.2
    default.geoip.example.com
    - a: 3.3.3.3
    as.foo.example.com
    - a: 1.1.1.1
    na.foo.example.com
    - a: 2.2.2.2
    default.foo.example.com
    - a: 3.3.3.3
  services:
    geoip.example.com:
    - "%cn.geoip.example.com"
    - default.geoip.example.com
    foo.example.com:
    - "%cn.foo.example.com"
    - default.foo.example.com
```
